[workspace]
authors = ["Nikita <github@nikiv.dev>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025061005,<26"
